name: Test on Ubuntu

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:

jobs:
  test-on-ubuntu:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        config: [Release, Debug]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install MOSEK
      run: |
        wget https://download.mosek.com/stable/10.2.6/mosektoolslinux64x86.tar.bz2
        tar xvf mosektoolslinux64x86.tar.bz2 -C /opt/
        echo "/opt/mosek/10.2/tools/platform/linux64x86/bin/" | sudo tee /etc/ld.so.conf.d/mosek.conf
        sudo ldconfig
        rm mosektoolslinux64x86.tar.bz2

    - name: Build
      run: |
        export MOSEKLM_LICENSE_FILE="${{ secrets.MOSEK_LICENSE }}"
        cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.config }}
        cmake --build build
        ctest --test-dir build
